import "@daesite/components/style"
import "./global.scss";
import {Icons} from "@daesite/components";
import type {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({children}: RootLayoutProps) => {
  return (
    <html lang="en">
      <body>
        <Icons />
        {children}
        <div
          id="__portalRoot"
          style={{position: "absolute", top: "0", left: "0"}}
        />
      </body>
    </html>
  );
};

export default RootLayout;
